export const CONSTANTS = {
	VARIANT: {
		solid: "solid",
		light: "light",
		dark: "dark",
		hallow: "hallow",
		ghost: "ghost",
	},
	ACCENT: {
		primary: "primary",
		secondary: "secondary",
		error: "error",
		info: "info",
		success: "success",
		warning: "warning",
		disabled: "disabled",
		image: "image",
	},
	SIZE: {
		default: "default",
		small: "small",
		large: "large",
		xtraLarge: "xtraLarge",
	},
	TYPE: {
		number: "number",
		roman: "roman",
		bullet: "bullet",
		image: "image",
	},
	primaryColor: "#1AB5EB",
	primaryHover: "1AB5EB0D",
	secondaryColor: "#7a7a7a",
	secondaryHover: "7a7a7a0D",
	error: "#eb3f27",
	errorHover:"#eb3f270D",
	warning: "#ffc107",
	warningHover: "ffc1070D",
	success: "#4ebd1e",
	successHover:"#4ebd1e0D",
	info: "#008FCB",
	infoHover:"#008FCB0D",
	hover: "#008FCB",
	textColor: "black",
	lightColor: "#F9F9F9",
	borderColor: " #DDDDDD",
	borderRadius: "4px",
	borderWidth: "1px",
	border: "1px solid",
	buttonColorPrimary: "#fff",
	buttonColorSecondary: "#fff",
	defaultSpacing: "8px",
	smSpacing: "5px",
	lgSpacing: "16px",
	xlSpacing: "24px",
	defaultFontsize: "14px",
	smFontsize: "13px",
	lgFontsize: "15px",
	xlFontsize: "16px",
	transaprantBackground: "transparent",
};

export const BackstageTheme = {
	VARIANT: {
		solid: "solid",
		light: "light",
		dark: "dark",
		hallow: "hallow",
		ghost: "ghost",
	},
	ACCENT: {
		primary: "primary",
		secondary: "secondary",
		error: "error",
		info: "info",
		success: "success",
		warning: "warning",
		disabled: "disabled",
		image: "image",
	},
	SIZE: {
		default: "default",
		small: "small",
		large: "large",
		xtraLarge: "xtraLarge",
	},
	TYPE: {
		number: "number",
		roman: "roman",
		bullet: "bullet",
		image: "image",
	},
	primaryColor: "#9D84B7",
	primaryHover: "1AB5EB0D",
	secondaryColor: "#a6a6a6",
	secondaryHover: "7a7a7a0D",
	error: "#FFB344",
	errorHover:"#eb3f270D",
	warning: "#FF7878",
	warningHover: "ffc1070D",
	success: "#80ED99",
	successHover:"#4ebd1e0D",
	info: "#1DB9C3",
	infoHover:"#008FCB0D",
	hover: "#008FCB",
	textColor: "black",
	lightColor: "#F9F9F9",
	borderColor: " #DDDDDD",
	borderRadius: "4px",
	borderWidth: "1px",
	border: "1px solid",
	buttonColorPrimary: "#fff",
	buttonColorSecondary: "#fff",
	defaultSpacing: "8px",
	smSpacing: "5px",
	lgSpacing: "16px",
	xlSpacing: "24px",
	defaultFontsize: "14px",
	smFontsize: "13px",
	lgFontsize: "15px",
	xlFontsize: "16px",
	transaprantBackground: "transparent",
};

export const CoreTheme = {
	VARIANT: {
		solid: "solid",
		light: "light",
		dark: "dark",
		hallow: "hallow",
		ghost: "ghost",
	},
	ACCENT: {
		primary: "primary",
		secondary: "secondary",
		error: "error",
		info: "info",
		success: "success",
		warning: "warning",
		disabled: "disabled",
		image: "image",
	},
	SIZE: {
		default: "default",
		small: "small",
		large: "large",
		xtraLarge: "xtraLarge",
	},
	TYPE: {
		number: "number",
		roman: "roman",
		bullet: "bullet",
		image: "image",
	},
	primaryColor: "-webkit-linear-gradient(147.14deg, #3E7BFA 6.95%, #6600CC 93.05%)",
	primaryHover: "1AB5EB0D",
	secondaryColor: "#555770",
	secondaryHover: "7a7a7a0D",
	error: "#FF3B3B",
	errorHover:"#eb3f270D",
	warning: "-webkit-linear-gradient(147.14deg, #FF8800 6.95%, #E63535 93.05%)",
	warningHover: "ffc1070D",
	success: "-webkit-linear-gradient(147.14deg, #00CFDE 6.95%, #05A660 93.05%)",
	successHover:"#4ebd1e0D",
	info: "-webkit-linear-gradient(147.14deg, #2574F4 6.95%, #0063F7 93.05%)",
	infoHover:"#008FCB0D",
	hover: "#008FCB",
	textColor: "black",
	lightColor: "#F9F9F9",
	borderColor: " #DDDDDD",
	borderRadius: "4px",
	borderWidth: "1px",
	border: "1px solid",
	buttonColorPrimary: "#fff",
	buttonColorSecondary: "#fff",
	defaultSpacing: "8px",
	smSpacing: "5px",
	lgSpacing: "16px",
	xlSpacing: "24px",
	defaultFontsize: "14px",
	smFontsize: "13px",
	lgFontsize: "15px",
	xlFontsize: "16px",
	transaprantBackground: "transparent",
};

export const CustomTheme = {
	VARIANT: {
		solid: "solid",
		light: "light",
		dark: "dark",
		hallow: "hallow",
		ghost: "ghost",
	},
	ACCENT: {
		primary: "primary",
		secondary: "secondary",
		error: "error",
		info: "info",
		success: "success",
		warning: "warning",
		disabled: "disabled",
		image: "image",
	},
	SIZE: {
		default: "default",
		small: "small",
		large: "large",
		xtraLarge: "xtraLarge",
	},
	TYPE: {
		number: "number",
		roman: "roman",
		bullet: "bullet",
		image: "image",
	},
	primaryColor: "",
	primaryHover: "1AB5EB0D",
	secondaryColor: "",
	secondaryHover: "7a7a7a0D",
	error: "",
	errorHover:"#eb3f270D",
	warning: "",
	warningHover: "ffc1070D",
	success: "",
	successHover:"#4ebd1e0D",
	info: "",
	infoHover:"#008FCB0D",
	hover: "#008FCB",
	textColor: "black",
	lightColor: "#F9F9F9",
	borderColor: " #DDDDDD",
	borderRadius: "4px",
	borderWidth: "1px",
	border: "1px solid",
	buttonColorPrimary: "#fff",
	buttonColorSecondary: "#fff",
	defaultSpacing: "8px",
	smSpacing: "5px",
	lgSpacing: "16px",
	xlSpacing: "24px",
	defaultFontsize: "14px",
	smFontsize: "13px",
	lgFontsize: "15px",
	xlFontsize: "16px",
	transaprantBackground: "transparent",
};

